# Cherry by r-lyeh (October 17 2018)
# Sexy cherry style
# From https://github.com/Patitotective/ImThemes

[Style]
Alpha = 1.0
DisabledAlpha = 0.6000000238418579
WindowPadding = [6.0, 3.0]
WindowRounding = 0.0
WindowBorderSize = 1.0
WindowMinSize = [32.0, 32.0]
WindowTitleAlign = [0.5, 0.5]
WindowMenuButtonPosition = "Left"
ChildRounding = 0.0
ChildBorderSize = 1.0
PopupRounding = 0.0
PopupBorderSize = 1.0
FramePadding = [5.0, 1.0]
FrameRounding = 3.0
FrameBorderSize = 1.0
ItemSpacing = [7.0, 1.0]
ItemInnerSpacing = [1.0, 1.0]
CellPadding = [4.0, 2.0]
IndentSpacing = 6.0
ColumnsMinSpacing = 6.0
ScrollbarSize = 13.0
ScrollbarRounding = 16.0
GrabMinSize = 20.0
GrabRounding = 2.0
TabRounding = 4.0
TabBorderSize = 1.0
TabMinWidthForCloseButton = 0.0
ColorButtonPosition = "Right"
ButtonTextAlign = [0.5, 0.5]
SelectableTextAlign = [0.0, 0.0]

[Colors]
Text = "#DBEDE2E0"
TextDisabled = "#DBEDE247"
WindowBg = "#21232B"
ChildBg = "#00000000"
PopupBg = "#333844E5"
Border = "#897A4129"
BorderShadow = "#00000000"
FrameBg = "#333844"
FrameBgHovered = "#74324CC6"
FrameBgActive = "#74324C"
TitleBg = "#3B3345"
TitleBgActive = "#801341"
TitleBgCollapsed = "#333844BF"
MenuBarBg = "#33384477"
ScrollbarBg = "#333844"
ScrollbarGrab = "#162628"
ScrollbarGrabHovered = "#74324CC6"
ScrollbarGrabActive = "#74324C"
CheckMark = "#B53844"
SliderGrab = "#77C4D323"
SliderGrabActive = "#B53844"
Button = "#77C4D323"
ButtonHovered = "#74324CDB"
ButtonActive = "#74324C"
Header = "#74324CC1"
HeaderHovered = "#74324CDB"
HeaderActive = "#801341"
Separator = "#6D6D7F7F"
SeparatorHovered = "#1966BFC6"
SeparatorActive = "#1966BF"
ResizeGrip = "#77C4D30A"
ResizeGripHovered = "#74324CC6"
ResizeGripActive = "#74324C"
Tab = "#2D5993DB"
TabHovered = "#4296F9CC"
TabActive = "#3268AD"
TabUnfocused = "#111A25F7"
TabUnfocusedActive = "#22426C"
PlotLines = "#DBEDE2A0"
PlotLinesHovered = "#74324C"
PlotHistogram = "#DBEDE2A0"
PlotHistogramHovered = "#74324C"
TableHeaderBg = "#303033"
TableBorderStrong = "#4F4F59"
TableBorderLight = "#3A3A3F"
TableRowBg = "#00000000"
TableRowBgAlt = "#FFFFFF0F"
TextSelectedBg = "#74324C6D"
DragDropTarget = "#FFFF00E5"
NavHighlight = "#4296F9"
NavWindowingHighlight = "#FFFFFFB2"
NavWindowingDimBg = "#CCCCCC33"
ModalWindowDimBg = "#CCCCCC59"
