# Classic by ocornut (August 14 2017)
# Classic Dear ImGui style
# From https://github.com/Patitotective/ImThemes

[Style]
Alpha = 1.0
DisabledAlpha = 0.6000000238418579
WindowPadding = [8.0, 8.0]
WindowRounding = 0.0
WindowBorderSize = 1.0
WindowMinSize = [32.0, 32.0]
WindowTitleAlign = [0.0, 0.5]
WindowMenuButtonPosition = "Left"
ChildRounding = 0.0
ChildBorderSize = 1.0
PopupRounding = 0.0
PopupBorderSize = 1.0
FramePadding = [4.0, 3.0]
FrameRounding = 0.0
FrameBorderSize = 0.0
ItemSpacing = [8.0, 4.0]
ItemInnerSpacing = [4.0, 4.0]
CellPadding = [4.0, 2.0]
IndentSpacing = 21.0
ColumnsMinSpacing = 6.0
ScrollbarSize = 14.0
ScrollbarRounding = 9.0
GrabMinSize = 10.0
GrabRounding = 0.0
TabRounding = 4.0
TabBorderSize = 0.0
TabMinWidthForCloseButton = 0.0
ColorButtonPosition = "Right"
ButtonTextAlign = [0.5, 0.5]
SelectableTextAlign = [0.0, 0.0]

[Colors]
Text = "#E5E5E5"
TextDisabled = "#999999"
WindowBg = "#000000D8"
ChildBg = "#00000000"
PopupBg = "#1C1C23EA"
Border = "#7F7F7F7F"
BorderShadow = "#00000000"
FrameBg = "#6D6D6D63"
FrameBgHovered = "#7777AF66"
FrameBgActive = "#6B68A3AF"
TitleBg = "#444489D3"
TitleBgActive = "#5151A0DD"
TitleBgCollapsed = "#6666CC33"
MenuBarBg = "#66668CCC"
ScrollbarBg = "#333F4C99"
ScrollbarGrab = "#6666CC4C"
ScrollbarGrabHovered = "#6666CC66"
ScrollbarGrabActive = "#6863CC99"
CheckMark = "#E5E5E57F"
SliderGrab = "#FFFFFF4C"
SliderGrabActive = "#6863CC99"
Button = "#59669B9E"
ButtonHovered = "#667AB5C9"
ButtonActive = "#7589CC"
Header = "#6666E572"
HeaderHovered = "#7272E5CC"
HeaderActive = "#8787DDCC"
Separator = "#7F7F7F99"
SeparatorHovered = "#9999B2"
SeparatorActive = "#B2B2E5"
ResizeGrip = "#FFFFFF19"
ResizeGripHovered = "#C6D1FF99"
ResizeGripActive = "#C6D1FFE5"
Tab = "#5555AEC8"
TabHovered = "#7272E5CC"
TabActive = "#6767B9D6"
TabUnfocused = "#484891D1"
TabUnfocusedActive = "#5959A6D5"
PlotLines = "#FFFFFF"
PlotLinesHovered = "#E5B200"
PlotHistogram = "#E5B200"
PlotHistogramHovered = "#FF9900"
TableHeaderBg = "#444460"
TableBorderStrong = "#4F4F72"
TableBorderLight = "#424247"
TableRowBg = "#00000000"
TableRowBgAlt = "#FFFFFF11"
TextSelectedBg = "#0000FF59"
DragDropTarget = "#FFFF00E5"
NavHighlight = "#7272E5CC"
NavWindowingHighlight = "#FFFFFFB2"
NavWindowingDimBg = "#CCCCCC33"
ModalWindowDimBg = "#33333359"
