# Darcula by ice1000 (August 07 2018)
# Poor simulation on IntelliJ's Darcula theme.
# From https://github.com/Patitotective/ImThemes

[Style]
Alpha = 1.0
DisabledAlpha = 0.6000000238418579
WindowPadding = [8.0, 8.0]
WindowRounding = 5.300000190734863
WindowBorderSize = 1.0
WindowMinSize = [32.0, 32.0]
WindowTitleAlign = [0.0, 0.5]
WindowMenuButtonPosition = "Left"
ChildRounding = 0.0
ChildBorderSize = 1.0
PopupRounding = 0.0
PopupBorderSize = 1.0
FramePadding = [4.0, 3.0]
FrameRounding = 2.299999952316284
FrameBorderSize = 1.0
ItemSpacing = [8.0, 6.5]
ItemInnerSpacing = [4.0, 4.0]
CellPadding = [4.0, 2.0]
IndentSpacing = 21.0
ColumnsMinSpacing = 6.0
ScrollbarSize = 14.0
ScrollbarRounding = 5.0
GrabMinSize = 10.0
GrabRounding = 2.299999952316284
TabRounding = 4.0
TabBorderSize = 0.0
TabMinWidthForCloseButton = 0.0
ColorButtonPosition = "Right"
ButtonTextAlign = [0.5, 0.5]
SelectableTextAlign = [0.0, 0.0]

[Colors]
Text = "#BBBBBB"
TextDisabled = "#585858"
WindowBg = "#3C3F41EF"
ChildBg = "#3C3F4100"
PopupBg = "#3C3F41EF"
Border = "#5555557F"
BorderShadow = "#28282800"
FrameBg = "#2B2B2B89"
FrameBgHovered = "#73ACFEAA"
FrameBgActive = "#787878AA"
TitleBg = "#0A0A0A"
TitleBgActive = "#00000082"
TitleBgCollapsed = "#28497A"
MenuBarBg = "#45494ACC"
ScrollbarBg = "#45494A99"
ScrollbarGrab = "#384F6B82"
ScrollbarGrabHovered = "#384F6B"
ScrollbarGrabActive = "#233143E8"
CheckMark = "#E5E5E5D3"
SliderGrab = "#B2B2B29E"
SliderGrabActive = "#4C4C4CD6"
Button = "#555A5C7C"
ButtonHovered = "#384F6B"
ButtonActive = "#233143"
Header = "#555A5C87"
HeaderHovered = "#73ACFEAA"
HeaderActive = "#787878AA"
Separator = "#505050"
SeparatorHovered = "#505050"
SeparatorActive = "#505050"
ResizeGrip = "#FFFFFFD8"
ResizeGripHovered = "#FFFFFF99"
ResizeGripActive = "#FFFFFFE5"
Tab = "#2D5993DB"
TabHovered = "#4296F9CC"
TabActive = "#3268AD"
TabUnfocused = "#111A25F7"
TabUnfocusedActive = "#22426C"
PlotLines = "#9B9B9B"
PlotLinesHovered = "#FF6D59"
PlotHistogram = "#E5B200"
PlotHistogramHovered = "#FF9900"
TableHeaderBg = "#303033"
TableBorderStrong = "#4F4F59"
TableBorderLight = "#3A3A3F"
TableRowBg = "#00000000"
TableRowBgAlt = "#FFFFFF0F"
TextSelectedBg = "#2F65CAE5"
DragDropTarget = "#FFFF00E5"
NavHighlight = "#4296F9"
NavWindowingHighlight = "#FFFFFFB2"
NavWindowingDimBg = "#CCCCCC33"
ModalWindowDimBg = "#CCCCCC59"
