# Dark Ruda by Raikiri (July 18 2019)
# Yet another dark theme.
# From https://github.com/Patitotective/ImThemes

[Style]
Alpha = 1.0
DisabledAlpha = 0.6000000238418579
WindowPadding = [8.0, 8.0]
WindowRounding = 0.0
WindowBorderSize = 1.0
WindowMinSize = [32.0, 32.0]
WindowTitleAlign = [0.0, 0.5]
WindowMenuButtonPosition = "Left"
ChildRounding = 0.0
ChildBorderSize = 1.0
PopupRounding = 0.0
PopupBorderSize = 1.0
FramePadding = [4.0, 3.0]
FrameRounding = 4.0
FrameBorderSize = 0.0
ItemSpacing = [8.0, 4.0]
ItemInnerSpacing = [4.0, 4.0]
CellPadding = [4.0, 2.0]
IndentSpacing = 21.0
ColumnsMinSpacing = 6.0
ScrollbarSize = 14.0
ScrollbarRounding = 9.0
GrabMinSize = 10.0
GrabRounding = 4.0
TabRounding = 4.0
TabBorderSize = 0.0
TabMinWidthForCloseButton = 0.0
ColorButtonPosition = "Right"
ButtonTextAlign = [0.5, 0.5]
SelectableTextAlign = [0.0, 0.0]

[Colors]
Text = "#F2F4F9"
TextDisabled = "#5B6B77"
WindowBg = "#1C262B"
ChildBg = "#262D38"
PopupBg = "#141414EF"
Border = "#14191E"
BorderShadow = "#00000000"
FrameBg = "#333F49"
FrameBgHovered = "#1E3347"
FrameBgActive = "#161E23"
TitleBg = "#161E23A5"
TitleBgActive = "#14191E"
TitleBgCollapsed = "#00000082"
MenuBarBg = "#262D38"
ScrollbarBg = "#05050563"
ScrollbarGrab = "#333F49"
ScrollbarGrabHovered = "#2D383F"
ScrollbarGrabActive = "#16354F"
CheckMark = "#478EFF"
SliderGrab = "#478EFF"
SliderGrabActive = "#5E9BFF"
Button = "#333F49"
ButtonHovered = "#478EFF"
ButtonActive = "#0F87F9"
Header = "#333F498C"
HeaderHovered = "#4296F9CC"
HeaderActive = "#4296F9"
Separator = "#333F49"
SeparatorHovered = "#1966BFC6"
SeparatorActive = "#1966BF"
ResizeGrip = "#4296F93F"
ResizeGripHovered = "#4296F9AA"
ResizeGripActive = "#4296F9F2"
Tab = "#1C262B"
TabHovered = "#4296F9CC"
TabActive = "#333F49"
TabUnfocused = "#1C262B"
TabUnfocusedActive = "#1C262B"
PlotLines = "#9B9B9B"
PlotLinesHovered = "#FF6D59"
PlotHistogram = "#E5B200"
PlotHistogramHovered = "#FF9900"
TableHeaderBg = "#303033"
TableBorderStrong = "#4F4F59"
TableBorderLight = "#3A3A3F"
TableRowBg = "#00000000"
TableRowBgAlt = "#FFFFFF0F"
TextSelectedBg = "#4296F959"
DragDropTarget = "#FFFF00E5"
NavHighlight = "#4296F9"
NavWindowingHighlight = "#FFFFFFB2"
NavWindowingDimBg = "#CCCCCC33"
ModalWindowDimBg = "#CCCCCC59"
