# Deep Dark by janekb04 (September 10 2021)
# Some colors are not set yet. Those are set to pure red notice that they have to be modified.
# From https://github.com/Patitotective/ImThemes

[Style]
Alpha = 1.0
DisabledAlpha = 0.6000000238418579
WindowPadding = [8.0, 8.0]
WindowRounding = 7.0
WindowBorderSize = 1.0
WindowMinSize = [32.0, 32.0]
WindowTitleAlign = [0.0, 0.5]
WindowMenuButtonPosition = "Left"
ChildRounding = 4.0
ChildBorderSize = 1.0
PopupRounding = 4.0
PopupBorderSize = 1.0
FramePadding = [5.0, 2.0]
FrameRounding = 3.0
FrameBorderSize = 1.0
ItemSpacing = [6.0, 6.0]
ItemInnerSpacing = [6.0, 6.0]
CellPadding = [6.0, 6.0]
IndentSpacing = 25.0
ColumnsMinSpacing = 6.0
ScrollbarSize = 15.0
ScrollbarRounding = 9.0
GrabMinSize = 10.0
GrabRounding = 3.0
TabRounding = 4.0
TabBorderSize = 1.0
TabMinWidthForCloseButton = 0.0
ColorButtonPosition = "Right"
ButtonTextAlign = [0.5, 0.5]
SelectableTextAlign = [0.0, 0.0]

[Colors]
Text = "#FFFFFF"
TextDisabled = "#7F7F7F"
WindowBg = "#191919"
ChildBg = "#00000000"
PopupBg = "#303030EA"
Border = "#30303049"
BorderShadow = "#0000003D"
FrameBg = "#0C0C0C89"
FrameBgHovered = "#30303089"
FrameBgActive = "#33383A"
TitleBg = "#000000"
TitleBgActive = "#0F0F0F"
TitleBgCollapsed = "#000000"
MenuBarBg = "#232323"
ScrollbarBg = "#0C0C0C89"
ScrollbarGrab = "#56565689"
ScrollbarGrabHovered = "#66666689"
ScrollbarGrabActive = "#8E8E8E89"
CheckMark = "#54AADB"
SliderGrab = "#56565689"
SliderGrabActive = "#8E8E8E89"
Button = "#0C0C0C89"
ButtonHovered = "#30303089"
ButtonActive = "#33383A"
Header = "#00000084"
HeaderHovered = "#0000005B"
HeaderActive = "#33383A54"
Separator = "#47474749"
SeparatorHovered = "#70707049"
SeparatorActive = "#667077"
ResizeGrip = "#47474749"
ResizeGripHovered = "#70707049"
ResizeGripActive = "#667077"
Tab = "#00000084"
TabHovered = "#232323"
TabActive = "#3333335B"
TabUnfocused = "#00000084"
TabUnfocusedActive = "#232323"
PlotLines = "#FF0000"
PlotLinesHovered = "#FF0000"
PlotHistogram = "#FF0000"
PlotHistogramHovered = "#FF0000"
TableHeaderBg = "#00000084"
TableBorderStrong = "#00000084"
TableBorderLight = "#47474749"
TableRowBg = "#00000000"
TableRowBgAlt = "#FFFFFF0F"
TextSelectedBg = "#33383A"
DragDropTarget = "#54AADB"
NavHighlight = "#FF0000"
NavWindowingHighlight = "#FF0000B2"
NavWindowingDimBg = "#FF000033"
ModalWindowDimBg = "#FF000059"
