# Enemymouse by enemymouse (August 15 2022)
# Retro theme
# From https://github.com/Patitotective/ImThemes

[Style]
Alpha = 1.0
DisabledAlpha = 0.6000000238418579
WindowPadding = [8.0, 8.0]
WindowRounding = 3.0
WindowBorderSize = 1.0
WindowMinSize = [32.0, 32.0]
WindowTitleAlign = [0.0, 0.5]
WindowMenuButtonPosition = "Left"
ChildRounding = 3.0
ChildBorderSize = 1.0
PopupRounding = 0.0
PopupBorderSize = 1.0
FramePadding = [4.0, 3.0]
FrameRounding = 3.0
FrameBorderSize = 0.0
ItemSpacing = [8.0, 4.0]
ItemInnerSpacing = [4.0, 4.0]
CellPadding = [4.0, 2.0]
IndentSpacing = 21.0
ColumnsMinSpacing = 6.0
ScrollbarSize = 14.0
ScrollbarRounding = 9.0
GrabMinSize = 20.0
GrabRounding = 1.0
TabRounding = 4.0
TabBorderSize = 0.0
TabMinWidthForCloseButton = 0.0
ColorButtonPosition = "Right"
ButtonTextAlign = [0.5, 0.5]
SelectableTextAlign = [0.0, 0.0]

[Colors]
Text = "#00FFFF"
TextDisabled = "#006668"
WindowBg = "#000000D3"
ChildBg = "#00000000"
PopupBg = "#283D3899"
Border = "#00FFFFA5"
BorderShadow = "#00000000"
FrameBg = "#70CCCC2D"
FrameBgHovered = "#70CCCC44"
FrameBgActive = "#70CEDBA8"
TitleBg = "#232D35BA"
TitleBgActive = "#00FFFF44"
TitleBgCollapsed = "#00000089"
MenuBarBg = "#00000033"
ScrollbarBg = "#38494CB5"
ScrollbarGrab = "#00FFFF70"
ScrollbarGrabHovered = "#00FFFFBC"
ScrollbarGrabActive = "#00FFFF"
CheckMark = "#00FFFFAD"
SliderGrab = "#00FFFF5B"
SliderGrabActive = "#00FFFFC1"
Button = "#00A5A575"
ButtonHovered = "#02FFFF6D"
ButtonActive = "#00FFFF9E"
Header = "#00FFFF54"
HeaderHovered = "#00FFFF6B"
HeaderActive = "#00FFFF89"
Separator = "#007F7F54"
SeparatorHovered = "#007F7F77"
SeparatorActive = "#00B2B2"
ResizeGrip = "#00FFFF89"
ResizeGripHovered = "#00FFFFBC"
ResizeGripActive = "#00FFFF"
Tab = "#2D5993DB"
TabHovered = "#4296F9CC"
TabActive = "#3268AD"
TabUnfocused = "#111A25F7"
TabUnfocusedActive = "#22426C"
PlotLines = "#00FFFF"
PlotLinesHovered = "#00FFFF"
PlotHistogram = "#00FFFF"
PlotHistogramHovered = "#00FFFF"
TableHeaderBg = "#303033"
TableBorderStrong = "#4F4F59"
TableBorderLight = "#3A3A3F"
TableRowBg = "#00000000"
TableRowBgAlt = "#FFFFFF0F"
TextSelectedBg = "#00FFFF38"
DragDropTarget = "#FFFF00E5"
NavHighlight = "#4296F9"
NavWindowingHighlight = "#FFFFFFB2"
NavWindowingDimBg = "#CCCCCC33"
ModalWindowDimBg = "#0A191682"
