# Green Font by aiekick (January 14 2021)
# Base theme (Green / Blue) of ImGuiFontStudio
# From https://github.com/Patitotective/ImThemes

[Style]
Alpha = 1.0
DisabledAlpha = 0.6000000238418579
WindowPadding = [8.0, 8.0]
WindowRounding = 0.0
WindowBorderSize = 1.0
WindowMinSize = [32.0, 32.0]
WindowTitleAlign = [0.0, 0.5]
WindowMenuButtonPosition = "Left"
ChildRounding = 0.0
ChildBorderSize = 1.0
PopupRounding = 0.0
PopupBorderSize = 1.0
FramePadding = [4.0, 3.0]
FrameRounding = 0.0
FrameBorderSize = 0.0
ItemSpacing = [8.0, 4.0]
ItemInnerSpacing = [4.0, 4.0]
CellPadding = [4.0, 2.0]
IndentSpacing = 21.0
ColumnsMinSpacing = 6.0
ScrollbarSize = 14.0
ScrollbarRounding = 9.0
GrabMinSize = 10.0
GrabRounding = 0.0
TabRounding = 4.0
TabBorderSize = 0.0
TabMinWidthForCloseButton = 0.0
ColorButtonPosition = "Right"
ButtonTextAlign = [0.5, 0.5]
SelectableTextAlign = [0.0, 0.0]

[Colors]
Text = "#FFFFFF"
TextDisabled = "#7F7F7F"
WindowBg = "#0F0F0FEF"
ChildBg = "#00000000"
PopupBg = "#141414EF"
Border = "#6D6D7F7F"
BorderShadow = "#00000000"
FrameBg = "#70707099"
FrameBgHovered = "#919191B2"
FrameBgActive = "#C1C1C1CC"
TitleBg = "#0A0A0A"
TitleBgActive = "#282828"
TitleBgCollapsed = "#00000099"
MenuBarBg = "#232323"
ScrollbarBg = "#05050587"
ScrollbarGrab = "#4F4F4F"
ScrollbarGrabHovered = "#686868"
ScrollbarGrabActive = "#828282"
CheckMark = "#21BF8CCC"
SliderGrab = "#21BFBFCC"
SliderGrabActive = "#21BFFFCC"
Button = "#21BF8C66"
ButtonHovered = "#21BFBF99"
ButtonActive = "#21BFFFCC"
Header = "#21BF8C66"
HeaderHovered = "#21BFBF99"
HeaderActive = "#21BFFFCC"
Separator = "#21BF8C66"
SeparatorHovered = "#21BFBF99"
SeparatorActive = "#21BFFFCC"
ResizeGrip = "#21BF8C66"
ResizeGripHovered = "#21BFBF99"
ResizeGripActive = "#21BFFFCC"
Tab = "#21BF8CCC"
TabHovered = "#21BFBFCC"
TabActive = "#21BFFFCC"
TabUnfocused = "#2D2D2D"
TabUnfocusedActive = "#5B5B5B89"
PlotLines = "#9B9B9B"
PlotLinesHovered = "#FF6D59"
PlotHistogram = "#E5B200"
PlotHistogramHovered = "#FF9900"
TableHeaderBg = "#303033"
TableBorderStrong = "#4F4F59"
TableBorderLight = "#3A3A3F"
TableRowBg = "#00000000"
TableRowBgAlt = "#FFFFFF11"
TextSelectedBg = "#4296F959"
DragDropTarget = "#FFFF00E5"
NavHighlight = "#4296F9"
NavWindowingHighlight = "#FFFFFFB2"
NavWindowingDimBg = "#CCCCCC33"
ModalWindowDimBg = "#CCCCCC59"
