# ledSynthmaster by olekristensen (August 15 2022)
# Soft gray theme
# From https://github.com/Patitotective/ImThemes

[Style]
Alpha = 1.0
DisabledAlpha = 0.6000000238418579
WindowPadding = [15.0, 15.0]
WindowRounding = 5.0
WindowBorderSize = 1.0
WindowMinSize = [32.0, 32.0]
WindowTitleAlign = [0.0, 0.5]
WindowMenuButtonPosition = "Left"
ChildRounding = 0.0
ChildBorderSize = 1.0
PopupRounding = 0.0
PopupBorderSize = 1.0
FramePadding = [5.0, 5.0]
FrameRounding = 4.0
FrameBorderSize = 0.0
ItemSpacing = [12.0, 8.0]
ItemInnerSpacing = [8.0, 6.0]
CellPadding = [4.0, 2.0]
IndentSpacing = 25.0
ColumnsMinSpacing = 6.0
ScrollbarSize = 15.0
ScrollbarRounding = 9.0
GrabMinSize = 5.0
GrabRounding = 3.0
TabRounding = 4.0
TabBorderSize = 0.0
TabMinWidthForCloseButton = 0.0
ColorButtonPosition = "Right"
ButtonTextAlign = [0.5, 0.5]
SelectableTextAlign = [0.0, 0.0]

[Colors]
Text = "#666360"
TextDisabled = "#666360C4"
WindowBg = "#EAE8E0B2"
ChildBg = "#FFF9F293"
PopupBg = "#FFF9F2"
Border = "#D6D3CCA5"
BorderShadow = "#EAE8E000"
FrameBg = "#FFF9F2"
FrameBgHovered = "#FCFF66C6"
FrameBgActive = "#42FF00"
TitleBg = "#FFF9F2"
TitleBgActive = "#3FFF00"
TitleBgCollapsed = "#FFF9F2BF"
MenuBarBg = "#FFF9F277"
ScrollbarBg = "#FFF9F2"
ScrollbarGrab = "#00000035"
ScrollbarGrabHovered = "#E5E800C6"
ScrollbarGrabActive = "#3FFF00"
CheckMark = "#3FFF00CC"
SliderGrab = "#00000023"
SliderGrabActive = "#3FFF00"
Button = "#00000023"
ButtonHovered = "#FCFF38DB"
ButtonActive = "#3FFF00"
Header = "#3FFF00C1"
HeaderHovered = "#3FFF00DB"
HeaderActive = "#3FFF00"
Separator = "#00000051"
SeparatorHovered = "#3FFF00C6"
SeparatorActive = "#3FFF00"
ResizeGrip = "#0000000A"
ResizeGripHovered = "#3FFF00C6"
ResizeGripActive = "#3FFF00"
Tab = "#2D5993DB"
TabHovered = "#4296F9CC"
TabActive = "#3268AD"
TabUnfocused = "#111A25F7"
TabUnfocusedActive = "#22426C"
PlotLines = "#666360A0"
PlotLinesHovered = "#3FFF00"
PlotHistogram = "#666360A0"
PlotHistogramHovered = "#3FFF00"
TableHeaderBg = "#303033"
TableBorderStrong = "#4F4F59"
TableBorderLight = "#3A3A3F"
TableRowBg = "#00000000"
TableRowBgAlt = "#FFFFFF0F"
TextSelectedBg = "#3FFF006D"
DragDropTarget = "#FFFF00E5"
NavHighlight = "#4296F9"
NavWindowingHighlight = "#FFFFFFB2"
NavWindowingDimBg = "#CCCCCC33"
ModalWindowDimBg = "#FFF9F2BA"
