# Microsoft by usernameiwantedwasalreadytaken (February 02 2018)
# Mimics (more or less) Microsoft Design Guidelines.
# From https://github.com/Patitotective/ImThemes

[Style]
Alpha = 1.0
DisabledAlpha = 0.6000000238418579
WindowPadding = [4.0, 6.0]
WindowRounding = 0.0
WindowBorderSize = 0.0
WindowMinSize = [32.0, 32.0]
WindowTitleAlign = [0.0, 0.5]
WindowMenuButtonPosition = "Left"
ChildRounding = 0.0
ChildBorderSize = 1.0
PopupRounding = 0.0
PopupBorderSize = 1.0
FramePadding = [8.0, 6.0]
FrameRounding = 0.0
FrameBorderSize = 1.0
ItemSpacing = [8.0, 6.0]
ItemInnerSpacing = [8.0, 6.0]
CellPadding = [4.0, 2.0]
IndentSpacing = 20.0
ColumnsMinSpacing = 6.0
ScrollbarSize = 20.0
ScrollbarRounding = 0.0
GrabMinSize = 5.0
GrabRounding = 0.0
TabRounding = 4.0
TabBorderSize = 0.0
TabMinWidthForCloseButton = 0.0
ColorButtonPosition = "Right"
ButtonTextAlign = [0.5, 0.5]
SelectableTextAlign = [0.0, 0.0]

[Colors]
Text = "#191919"
TextDisabled = "#7F7F7F"
WindowBg = "#F2F2F2"
ChildBg = "#F2F2F2"
PopupBg = "#FFFFFF"
Border = "#999999"
BorderShadow = "#00000000"
FrameBg = "#FFFFFF"
FrameBgHovered = "#0077D633"
FrameBgActive = "#0077D6"
TitleBg = "#0A0A0A"
TitleBgActive = "#28497A"
TitleBgCollapsed = "#00000082"
MenuBarBg = "#DBDBDB"
ScrollbarBg = "#DBDBDB"
ScrollbarGrab = "#AFAFAF"
ScrollbarGrabHovered = "#00000033"
ScrollbarGrabActive = "#0000007F"
CheckMark = "#191919"
SliderGrab = "#AFAFAF"
SliderGrabActive = "#0000007F"
Button = "#DBDBDB"
ButtonHovered = "#0077D633"
ButtonActive = "#0077D6"
Header = "#DBDBDB"
HeaderHovered = "#0077D633"
HeaderActive = "#0077D6"
Separator = "#6D6D7F7F"
SeparatorHovered = "#1966BFC6"
SeparatorActive = "#1966BF"
ResizeGrip = "#4296F933"
ResizeGripHovered = "#4296F9AA"
ResizeGripActive = "#4296F9F2"
Tab = "#2D5993DB"
TabHovered = "#4296F9CC"
TabActive = "#3268AD"
TabUnfocused = "#111A25F7"
TabUnfocusedActive = "#22426C"
PlotLines = "#9B9B9B"
PlotLinesHovered = "#FF6D59"
PlotHistogram = "#E5B200"
PlotHistogramHovered = "#FF9900"
TableHeaderBg = "#303033"
TableBorderStrong = "#4F4F59"
TableBorderLight = "#3A3A3F"
TableRowBg = "#00000000"
TableRowBgAlt = "#FFFFFF0F"
TextSelectedBg = "#4296F959"
DragDropTarget = "#FFFF00E5"
NavHighlight = "#4296F9"
NavWindowingHighlight = "#FFFFFFB2"
NavWindowingDimBg = "#CCCCCC33"
ModalWindowDimBg = "#CCCCCC59"
