# Photoshop by Derydoca (February 14 2019)
# Inspired by Photoshop's UI.
# From https://github.com/Patitotective/ImThemes

[Style]
Alpha = 1.0
DisabledAlpha = 0.6000000238418579
WindowPadding = [8.0, 8.0]
WindowRounding = 4.0
WindowBorderSize = 1.0
WindowMinSize = [32.0, 32.0]
WindowTitleAlign = [0.0, 0.5]
WindowMenuButtonPosition = "Left"
ChildRounding = 4.0
ChildBorderSize = 1.0
PopupRounding = 2.0
PopupBorderSize = 1.0
FramePadding = [4.0, 3.0]
FrameRounding = 2.0
FrameBorderSize = 1.0
ItemSpacing = [8.0, 4.0]
ItemInnerSpacing = [4.0, 4.0]
CellPadding = [4.0, 2.0]
IndentSpacing = 21.0
ColumnsMinSpacing = 6.0
ScrollbarSize = 13.0
ScrollbarRounding = 12.0
GrabMinSize = 7.0
GrabRounding = 0.0
TabRounding = 0.0
TabBorderSize = 1.0
TabMinWidthForCloseButton = 0.0
ColorButtonPosition = "Right"
ButtonTextAlign = [0.5, 0.5]
SelectableTextAlign = [0.0, 0.0]

[Colors]
Text = "#FFFFFF"
TextDisabled = "#7F7F7F"
WindowBg = "#2D2D2D"
ChildBg = "#47474700"
PopupBg = "#4F4F4F"
Border = "#434343"
BorderShadow = "#00000000"
FrameBg = "#282828"
FrameBgHovered = "#333333"
FrameBgActive = "#474747"
TitleBg = "#252525"
TitleBgActive = "#252525"
TitleBgCollapsed = "#252525"
MenuBarBg = "#313131"
ScrollbarBg = "#282828"
ScrollbarGrab = "#464646"
ScrollbarGrabHovered = "#4C4C4C"
ScrollbarGrabActive = "#FF6300"
CheckMark = "#FFFFFF"
SliderGrab = "#636363"
SliderGrabActive = "#FF6300"
Button = "#FFFFFF00"
ButtonHovered = "#FFFFFF27"
ButtonActive = "#FFFFFF63"
Header = "#4F4F4F"
HeaderHovered = "#777777"
HeaderActive = "#777777"
Separator = "#434343"
SeparatorHovered = "#636363"
SeparatorActive = "#FF6300"
ResizeGrip = "#FFFFFF3F"
ResizeGripHovered = "#FFFFFFAA"
ResizeGripActive = "#FF6300"
Tab = "#181818"
TabHovered = "#595959"
TabActive = "#313131"
TabUnfocused = "#181818"
TabUnfocusedActive = "#313131"
PlotLines = "#777777"
PlotLinesHovered = "#FF6300"
PlotHistogram = "#959595"
PlotHistogramHovered = "#FF6300"
TableHeaderBg = "#303033"
TableBorderStrong = "#4F4F59"
TableBorderLight = "#3A3A3F"
TableRowBg = "#00000000"
TableRowBgAlt = "#FFFFFF0F"
TextSelectedBg = "#FFFFFF27"
DragDropTarget = "#FF6300"
NavHighlight = "#FF6300"
NavWindowingHighlight = "#FF6300"
NavWindowingDimBg = "#00000095"
ModalWindowDimBg = "#00000095"
