# Soft Cherry by Patitotective (June 18 2022)
# A cuter version of Cherry.
# From https://github.com/Patitotective/ImThemes

[Style]
Alpha = 1.0
DisabledAlpha = 0.4000000059604645
WindowPadding = [10.0, 10.0]
WindowRounding = 4.0
WindowBorderSize = 0.0
WindowMinSize = [50.0, 50.0]
WindowTitleAlign = [0.5, 0.5]
WindowMenuButtonPosition = "Left"
ChildRounding = 0.0
ChildBorderSize = 1.0
PopupRounding = 1.0
PopupBorderSize = 1.0
FramePadding = [5.0, 3.0]
FrameRounding = 3.0
FrameBorderSize = 0.0
ItemSpacing = [6.0, 6.0]
ItemInnerSpacing = [3.0, 2.0]
CellPadding = [3.0, 3.0]
IndentSpacing = 6.0
ColumnsMinSpacing = 6.0
ScrollbarSize = 13.0
ScrollbarRounding = 16.0
GrabMinSize = 20.0
GrabRounding = 4.0
TabRounding = 4.0
TabBorderSize = 1.0
TabMinWidthForCloseButton = 0.0
ColorButtonPosition = "Right"
ButtonTextAlign = [0.5, 0.5]
SelectableTextAlign = [0.0, 0.0]

[Colors]
Text = "#DBEDE2"
TextDisabled = "#858C88"
WindowBg = "#21232B"
ChildBg = "#262830"
PopupBg = "#333844"
Border = "#231D22"
BorderShadow = "#000000"
FrameBg = "#2B2F3B"
FrameBgHovered = "#74324C"
FrameBgActive = "#74324C"
TitleBg = "#3B3345"
TitleBgActive = "#801341"
TitleBgCollapsed = "#333844"
MenuBarBg = "#333844"
ScrollbarBg = "#3D3D38"
ScrollbarGrab = "#63635F"
ScrollbarGrabHovered = "#B1B1AF"
ScrollbarGrabActive = "#B1B1AF"
CheckMark = "#A8232D"
SliderGrab = "#A62658"
SliderGrabActive = "#B53844"
Button = "#A62658"
ButtonHovered = "#74324C"
ButtonActive = "#74324C"
Header = "#74324C"
HeaderHovered = "#A62658"
HeaderActive = "#801341"
Separator = "#6D6D7F"
SeparatorHovered = "#1966BF"
SeparatorActive = "#1966BF"
ResizeGrip = "#A62658"
ResizeGripHovered = "#74324C"
ResizeGripActive = "#74324C"
Tab = "#2D5993"
TabHovered = "#4296F9"
TabActive = "#3268AD"
TabUnfocused = "#111A25"
TabUnfocusedActive = "#22426C"
PlotLines = "#DBEDE2"
PlotLinesHovered = "#74324C"
PlotHistogram = "#4FC632"
PlotHistogramHovered = "#74324C"
TableHeaderBg = "#303033"
TableBorderStrong = "#4F4F59"
TableBorderLight = "#3A3A3F"
TableRowBg = "#000000"
TableRowBgAlt = "#FFFFFF"
TextSelectedBg = "#62A0EA"
DragDropTarget = "#FFFF00"
NavHighlight = "#4296F9"
NavWindowingHighlight = "#FFFFFF"
NavWindowingDimBg = "#CCCCCC"
ModalWindowDimBg = "#CCCCCC4C"
