# Unreal by dev0-1 (August 22 2018)
# Inspirated from UE4.
# From https://github.com/Patitotective/ImThemes

[Style]
Alpha = 1.0
DisabledAlpha = 0.6000000238418579
WindowPadding = [8.0, 8.0]
WindowRounding = 0.0
WindowBorderSize = 1.0
WindowMinSize = [32.0, 32.0]
WindowTitleAlign = [0.0, 0.5]
WindowMenuButtonPosition = "Left"
ChildRounding = 0.0
ChildBorderSize = 1.0
PopupRounding = 0.0
PopupBorderSize = 1.0
FramePadding = [4.0, 3.0]
FrameRounding = 0.0
FrameBorderSize = 0.0
ItemSpacing = [8.0, 4.0]
ItemInnerSpacing = [4.0, 4.0]
CellPadding = [4.0, 2.0]
IndentSpacing = 21.0
ColumnsMinSpacing = 6.0
ScrollbarSize = 14.0
ScrollbarRounding = 9.0
GrabMinSize = 10.0
GrabRounding = 0.0
TabRounding = 4.0
TabBorderSize = 0.0
TabMinWidthForCloseButton = 0.0
ColorButtonPosition = "Right"
ButtonTextAlign = [0.5, 0.5]
SelectableTextAlign = [0.0, 0.0]

[Colors]
Text = "#FFFFFF"
TextDisabled = "#7F7F7F"
WindowBg = "#0F0F0FEF"
ChildBg = "#FFFFFF00"
PopupBg = "#141414EF"
Border = "#6D6D7F7F"
BorderShadow = "#00000000"
FrameBg = "#33353889"
FrameBgHovered = "#66666666"
FrameBgActive = "#2D2D2DAA"
TitleBg = "#0A0A0A"
TitleBgActive = "#494949"
TitleBgCollapsed = "#00000082"
MenuBarBg = "#232323"
ScrollbarBg = "#05050587"
ScrollbarGrab = "#4F4F4F"
ScrollbarGrabHovered = "#686868"
ScrollbarGrabActive = "#828282"
CheckMark = "#EFEFEF"
SliderGrab = "#828282"
SliderGrabActive = "#DBDBDB"
Button = "#70707066"
ButtonHovered = "#75777A"
ButtonActive = "#6B6B6B"
Header = "#B2B2B24F"
HeaderHovered = "#B2B2B2CC"
HeaderActive = "#7A7F84"
Separator = "#6D6D7F7F"
SeparatorHovered = "#B7B7B7C6"
SeparatorActive = "#828282"
ResizeGrip = "#E8E8E83F"
ResizeGripHovered = "#CECECEAA"
ResizeGripActive = "#757575F2"
Tab = "#2D5993DB"
TabHovered = "#4296F9CC"
TabActive = "#3268AD"
TabUnfocused = "#111A25F7"
TabUnfocusedActive = "#22426C"
PlotLines = "#9B9B9B"
PlotLinesHovered = "#FF6D59"
PlotHistogram = "#BA9926"
PlotHistogramHovered = "#FF9900"
TableHeaderBg = "#303033"
TableBorderStrong = "#4F4F59"
TableBorderLight = "#3A3A3F"
TableRowBg = "#00000000"
TableRowBgAlt = "#FFFFFF0F"
TextSelectedBg = "#DDDDDD59"
DragDropTarget = "#FFFF00E5"
NavHighlight = "#999999"
NavWindowingHighlight = "#FFFFFFB2"
NavWindowingDimBg = "#CCCCCC33"
ModalWindowDimBg = "#CCCCCC59"
